### ISSUE TITLE
Feature Request: Ability to disable an override but save the url ( toggle on and off )

### ISSUE THREAD

**Issue by northkode** [joeldenning/import-map-overrides#10]
Would be handy to be able to toggle an override on or off just to switch back and forth instead of only reset to default. 

Handy when you are testing local and server and testing deployments.

**Comment by joeldenning** [comment]
I agree this would be nice. Want to send in a pull request that implements this?

**Comment by northkode** [comment]
@joeldenning i'll take a peak at this this weekend! Cheers!

**Comment by joeldenning** [comment]
No objection at all - would be nice to make it look better

**Comment by joeldenning** [comment]
Regarding implementation - I think that either the key or the value of the local storage entry could indicate a disabled override. I also think that this functionality should be surfaced via the javascript api, not just through the UI

**Comment by northkode** [comment]
@joeldenning  ok sounds good. I was thinking that i would change the layout a bit to make it a bit easier to manage teh overrides and enable a check box for override modules for "enable|disable" and the keep the reset to remove it. Something similar to below: (not done obviously)
![image](https://user-images.githubusercontent.com/6988083/76136099-13102580-5feb-11ea-8ee5-e09e128c9716.png)

**Comment by joeldenning** [comment]
I like the changes to the layout - I think two columns will make it better.

Regarding the "Enabled?" checkbox, I think it could be named better and I think it should default to the override being applied/enabled.

Here are a couple options for the UI that I think would be more clear to the user:

1. Move the checkbox way closer to the "react" button, so it doesn't look like it's connected to the default modules instead of the overridden module. Name the column "Disable override"
2. Alternatively, don't show the checkbox in the module list. Instead, make the disabled override a new color (blue?). Once they click on the module, show a checkbox that says "Override disabled"

I'm fine with either of the options (and small variations of them), but think that option 2 might be the best UX. What do you think?

**Comment by northkode** [comment]
@joeldenning  Ill play with those suggestion. I'll wire it all up and get it working and submit a PR  and if you have any tweaks maybe we can tag team it.

**Comment by joeldenning** [comment]
👍 sounds good

**Comment by joeldenning** [comment]
@northkode any update on this? If you aren't going to be able to get to this this weekend, I might be able to work on this this weekend. If you'd like that, could you push up your code and create a wip PR? Also, if you'd like to finish this out yourself that's 100% okay, too

**Comment by northkode** [comment]
@joeldenning hey man, got hit with a bug and havent been up to coding last couple days. Ill send you my code so far. Thanks for your help!
