### ISSUE TITLE
sometimes port number doesn't get converted to a URL

### ISSUE THREAD

**Issue by joeldenning** [joeldenning/import-map-overrides#27]

**Comment by headquarters** [comment]
Hi, I think I'm running into this issue. I wanted to check if we're talking about the same thing before filing a separate issue. I assume if you press Apply Override, it should always apply the override. It looks like applying the same override a 2nd time (or n+1 times) toggles between the current domain and localhost, even though the derived URL shows up as localhost in the pop up. Is that what this issue is about? I started looking into creating a fix, but don't have time to step through all the logic right now. If I find time, I'll try to come back to help out with this.

![2021-06-03 11 22 29](https://user-images.githubusercontent.com/347079/120670189-2e701780-c45e-11eb-8090-c72804c57374.gif)

**Comment by joeldenning** [comment]
Thanks for explaining how to reproduce the problem - yes it's the same thing as what I originally reported. I will look into this right now and see if the fix is easy. If I don't get around to fixing it today, feel free to submit a PR with the fix (would be much appreciated!).

**Comment by joeldenning** [comment]
Fix released in https://github.com/joeldenning/import-map-overrides/releases/tag/v2.3.3
