### ISSUE TITLE
Using import-map-overrides for making an 'in-browser' IDE.

### ISSUE THREAD

**Issue by LeifAndersen** [joeldenning/import-map-overrides#54]
You say multiple times in the documentation that its risky to use import-map-overrides in production (and to use it only during development). I'm putting together a browser-based IDE, and it seems like import-map-overrides is the only way to let users of the IDE link to external dependencies.

I understand that doing this opens up arbitrary code execution and self-xss attacks. But those are par for the course for an IDE anyway. (Wouldn't be much of an IDE if you couldn't run code in it after all. ;) )

I'm curious if this is the security (and probably performance) implications are the only reasons you say to not do this, or are there other reasons too?  (And if it really is a bad idea to use import-map-overrides, is there any other way to create a dynamic import-map type of thing (or a lexically scoped import-map)).

Thanks.

**Comment by joeldenning** [comment]
Security is the only reason to not use import-map-overrides in production. I have used it in production and it works great. Performance overhead is not really a concern, as import-map-overrides just inserts a `<script>` into the DOM after reading local storage, and neither of those are extremely slow (especially since it doesn't read all values of local storage, which could be long and slow to read, but only the import-map-overrides: local storage values).

I don't see any reason not to use import-map-overrides in production - I wish you best of luck in doing so!
