### ISSUE TITLE
IE 11 broken

### ISSUE THREAD

**Issue by nilzona** [joeldenning/import-map-overrides#58]
Not sure if this library is promising support for IE11, but I saw in the README description that it does.

This commit https://github.com/joeldenning/import-map-overrides/commit/6e0f50e30f38f387f8ffb1c0f54405fe2563811b#r52817708

Seems to have broken `import-map-overrides` in IE11.

**Comment by joeldenning** [comment]
import-map-overrides is compiled by babel before being published to npm. See https://cdn.jsdelivr.net/npm/import-map-overrides@2.4.0/dist/import-map-overrides.js, which shows that there are no template strings in the published code. Specifically, the line you linked to is compiled to the following, which does not contain template strings:

```js
setTimeout((function(){var t="import-map-overrides:".concat(e),n=o?new CustomEvent(t):document.createEvent(t);window.dispatchEvent(n)}
```

I'm pretty confident that the javascript API for import-map-overrides works in IE11 (I used it a few weeks ago), but I think the UI for it might be broken (haven't tested it in a while). Could you provide more specific details about any errors/problems you see, and whether they apply to the UI or the JS API for import-map-overrides? I am on limited internet connection with a Macbook and cannot easily test IE11 right now.

**Comment by corwinm** [comment]
Ran into this one today.

The problem is actually with the fallback `document.createEvent()`. According to https://caniuse.com/customevent you need to also call `e.initCustomEvent(...)` on the event created.
If you are in a hurry for a workaround you can try to pollyfill from MDN https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#polyfill

I would even possibly prefer the pollyfill as a long term solution over a fix for the library, but that is just my opinion.

**Comment by joeldenning** [comment]
Thanks @corwinm. #59 fixes the problem with custom events and i've confirmed that the javascript api for import map overrides works in IE11. The UI for import map overrides almost works in IE11 with a custom events polyfill, but it appears that preact might have a part that doesn't support IE11 so adding new modules to override didn't work for me.

**Comment by joeldenning** [comment]
Fix released in https://github.com/joeldenning/import-map-overrides/releases/tag/v2.4.1
